Stage one
VictorKholyavo/basic-crm pull request #1
Opened 2019-02-13 15:25 UTC by VictorKholyavo

2019-02-14 14:35 UTC, HelgaListopad requested changes

2019-02-14 14:35 UTC, HelgaListopad commented on index.html
> +	<script type="text/javascript" src="codebase/webix.js"></script>
`codebase` помечена в gitignore (что правильно).
Но в проекте вебикса фактически нет - перенеси его в какую-то другую папку (чтобы путь отличался от от myapp.js) и добавь в репозиторий.

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/activities.js
> +<<<<<<< HEAD
Линт эту строку не пропустил, кстати.
Ну и тестируй свой код, пожалуйста, перед pull request

2019-02-14 14:35 UTC, HelgaListopad commented on sources/models/activities.js
> +				var parser = webix.Date.strToDate("%d-%m-%Y %H:%i");
$init срабатывает на каждом отдельном айтеме - parser лучше вынести из этого метода куда-то за пределы коллекции. В целом, логику и переменные, которые используются кучу раз, лучше всегда "выносить за скобки"

2019-02-14 14:35 UTC, HelgaListopad commented on sources/models/activities.js
> +				var parser = webix.Date.strToDate("%d-%m-%Y %H:%i");
ES6 consistency: `var` -> `let` or `const` everywhere

2019-02-14 14:35 UTC, HelgaListopad commented on sources/models/activities.js
> +			if (obj.id) {
ID нет == строка новая, а из формы по Add activity попадает дата как строка.
Если хочешь вставить проверку - лучше это делать через `typeof obj.DueDate`, чтобы понять, формат не тот

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/activities.js
> +							);
Из всего этого метода тоже лучше возвращать `false;`, иначе без webix.confirm вылетела бы нехорошая ошибка.

Клики обрабатываются примерно так
onClick на класс в строке -> onItemClick -> обработка select

Поэтому после удаления айтема дальнейшую обработку клика из onClick нужно блокировать.

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/activities.js
> +		var id = this.getParam("id");
`var` -> `let` or `const`

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/contacts.js
> +				list.select(id);
select() вызовет событие onAfterSelect, поэтому setParam здесь не очень-то и нужен

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/contacts.js
> +									editable: true,
Вообще, это свойство здесь не нужно.

Кроме того, у листа по умолчанию нет поддержки editable - нужно [подключить модуль edit ability](https://docs.webix.com/desktop__edit.html#editingotheruirelatedcomponents)

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/data.js
> +export default class DataView extends JetView{
В приложении дважды объявлен класс DataView - насколько я вижу, этот нигде не используется

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/form.js
> +		var form = {
`var` -> `let` or `const`

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/form.js
> +					stringResult:true,
Возвращает строку, которая попадает в коллекцию вместо date object. 
В таблице со строками не будет работать сортировка и фильтрация, а format для колонки DueDate вполне может показать что-то не то. Так что DueDate (основное поле для работы с датой) внутри приложения нужно всегда оставлять объектом.
С точки зрения отправки на сервер тебе "повезло" - stringResult конвертирует дату в соответствии с локалью через [parseFormatStr](https://docs.webix.com/api__i18n_parseformatstr.html), который по умолчанию (только в английской локали) соответствует тому, во что вы должны были преобразовать дату через $save коллекции.

2019-02-14 14:35 UTC, HelgaListopad commented on sources/models/activities.js
> +		}
Здесь я ожидала увидеть $save с нужным преобразованием. 
Проблема в том, что код должен оставаться читабельным с возоможностью его потом доработать. То, работает "каким-то чудом", очень сложно потом поддерживатьи чинить, если что-то пошло не так. 

Правильная строка сейчас уходит на сервер благодаря `stringResult` datepicker'a.
А если ты редактировал State через чекбокс прямо из таблицы, то тут тоже "повезло" с автоматическим преобразованием - перед отправкой Webix сам прогоняет date object через [parseFormat](https://docs.webix.com/api__i18n_parseformat_other.html), который тоже зависит от текущей локали. Такой зависимости быть не должно, т.к. если локаль поменять - сервер уже не получит строку нужного формата.

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/detailes.js
> +				template.setValues(values);
```
var template = this.$$("detailedInfo");
template.setValues(values);
```
и 
```
this.$$("detailedInfo").parse(item);
```
лучше объединить.
А чтобы не менять исходный объект (values), бери его как `webix.copy( contacts.getItem(id) )`

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/form.js
> +							const filled = this.getParentView().getValues();
Код для клика из обеих кнопок мало отличается, поэтому хорошо бы вынести всё одинаковое в отдельный метод (или вынести всё и сделать проверку на то, добавляется или редактируется айтем)

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/form.js
> +							this.getTopParentView().hide();
Вот на этом этапе хорошо бы ещё очистить окно и сбросить валидацию

2019-02-14 14:35 UTC, HelgaListopad commented on sources/views/form.js
> +	showWindow(){
showWindow и showEmptyWindow можно было бы объединить в один метод (т.к. много похожего кода).
Передавать в него, например, параметр mode (add или edit) и в зависимости от него прятать/показывать нужный заголовок/кнопку. 
Писать несколько раз одинаковый код в принципе не очень хорошо)

2019-02-15 17:19 UTC, Zwillinge commented on sources/views/contacts.js
> +									editable: true,
и рядом `autoConfig:true` также не имеет никакого значения для листа

2019-02-15 17:37 UTC, Zwillinge commented on sources/views/form.js
> +	showWindow(){
стало лучше, но что-то не так с логикой. передается mode первым параметром , а вторым или "" или ничего.  поэтому внутри метода проверка на этот параметр ( `if(idOfContact)` ) никогда не проходит

2019-02-15 17:50 UTC, Zwillinge requested changes

2019-02-15 17:50 UTC, Zwillinge commented on sources/models/contacts.js
> +			obj.value = obj.FirstName + " " + obj.LastName;
если мы отредактируем имя и фамилию контакта (stage 2), value останется таким же. здесь имеет смысл на поменять на $change

2019-02-15 17:50 UTC, Zwillinge commented on sources/models/records.js
> +export const data = new webix.DataCollection({ data:[
оно не используется, зачем хранить мусор в приложении?

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/activities.js
> +								let mode = "add";
лишняя переменная, this.win4.showWindow("add"); по поводу второго параметра, см. соседний коммент , есть вероятность того, что он бесполезный

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/activities.js
> +							this.win4.showWindow(mode);
`this.win4.showWindow("edit");` - незачем хранить эту строку

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/activities.js
> +			this.$$("datatable").refresh();
а зачем рефрешить таблицу? это делается по клику на иконку редактирования, но зачем..

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/detailes.js
> +			let id = this.getParam("id", true);
а если нет параметра в url-е? здесь как и в модуле контактов надо проверять наличие такого элемента в коллекции, иначе я могу сейчас написать что угодно в адресной строке, а этот модуль сгенерирует ошибку

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/detailes.js
> +				item.status = statuses.getItem(item.StatusID).Value;
проверка на наличие StatusID у контакта и соответствующего статуса в коллекции весьма не помешала бы

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/form.js
> +				template:"asdasdasd",
чтобы webix понимал, что это темплейт, можно напрямую указать `view:"template"` , а если хочется непустого темплейта, то это можно сделать чище как `template:" "`

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/form.js
> +			form.clear();
мы уже чистим форму на `onHide`

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/form.js
> +			if (idOfContact) {
idOfContact  - всегда пустая переменная

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/form.js
> +			formTemplate.refresh();
рефреш темплейта и показ окна можно вынести за скобки и выполнить после обоих блоков, чтобы не повторяться

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/form.js
> +			if(filled.id && activities.exists(filled.id)) {
а проверка на exists точно нужна? у нас модальное окно, пользователь не смог бы удалить эту activity

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/form.js
> +				webix.message("All is correct");
показ сообщения не надо дублировать, нужно вынести за скобки

2019-02-15 17:50 UTC, Zwillinge commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
вместо того, чтобы полагаться на id, лучше брать `item.value`

```
onAfterSelect: function(id) {
	const header =this.$scope("header");
	header.define({ template: this.getItem(id).value });
	header.refresh();
}	
```

2019-02-16 10:07 UTC, VictorKholyavo commented on sources/views/form.js
> +	showWindow(){
Параметр idOfContact нужен для stage 2, когда форма добавления activity используется во вкладке Contacts. Тогда контакт выставляется в форме во вкладке ContactID и окно для изменения имени контакта блокируется. Мне нужно удалить из этого stage или можно оставить?

2019-02-16 10:08 UTC, VictorKholyavo commented on sources/views/contacts.js
> +									editable: true,
Удалил

2019-02-16 10:10 UTC, VictorKholyavo commented on sources/models/records.js
> +export const data = new webix.DataCollection({ data:[
Удалил

2019-02-16 10:18 UTC, VictorKholyavo commented on sources/views/activities.js
> +			this.$$("datatable").refresh();
У меня была проблема с датами и я не знал как решить проблему. Сейчас удалил

2019-02-16 10:33 UTC, VictorKholyavo commented on sources/views/detailes.js
> +			let id = this.getParam("id", true);
Добавил проверку id. Если id из url'a не найден в коллекции, то выбирается первый элемент в коллекции и url выставляется на него же

2019-02-16 10:44 UTC, VictorKholyavo commented on sources/views/detailes.js
> +				item.status = statuses.getItem(item.StatusID).Value;
Добавил проверку на наличие StatusID у контакта и соответствующего статуса в коллекции

2019-02-16 10:59 UTC, VictorKholyavo commented on sources/models/contacts.js
> +			obj.value = obj.FirstName + " " + obj.LastName;
Исправил

2019-02-16 11:00 UTC, VictorKholyavo commented on sources/views/form.js
> +				template:"asdasdasd",
Исправил на:
`head: {
template: " ",
}`

2019-02-16 11:02 UTC, VictorKholyavo commented on sources/views/form.js
> +			formTemplate.refresh();
Исправил

2019-02-16 11:02 UTC, VictorKholyavo commented on sources/views/form.js
> +			if (idOfContact) {
Параметр idOfContact нужен для stage 2, когда форма добавления activity используется во вкладке Contacts. Тогда контакт выставляется в форме во вкладке ContactID и окно для изменения имени контакта блокируется. Мне нужно удалить из этого stage или можно оставить?

2019-02-16 11:04 UTC, VictorKholyavo commented on sources/views/form.js
> +			if(filled.id && activities.exists(filled.id)) {
Исправил

2019-02-16 11:04 UTC, VictorKholyavo commented on sources/views/form.js
> +				webix.message("All is correct");
Исправил

2019-02-16 11:05 UTC, VictorKholyavo commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
Исправил

2019-02-17 09:02 UTC, Zwillinge commented on sources/views/form.js
> +	showWindow(){
Логика для stage 2 должна находиться в stage 2. 

Кроме этого, на второй стадии могут возникнуть проблемы с получением данных для формы. Они сейчас берутся как ` this.getParam("id", true);` а parent View может быть как модуль contacts, так и activities, и id означает в них разные вещи.  

Поэтому давай сейчас мы удалим логику stage  2, а в соседней ветке внимательно подумаем как это правильно разрешить.

2019-02-17 09:05 UTC, Zwillinge commented on sources/views/detailes.js
> +				item.status = statuses.getItem(item.StatusID).Value;
проверка на наличие деалется через `exists`, а твоя записть ` statuses.getItem(values.StatusID).Value` бросит ошибку, если нет такого статуса, т.е. попытается считать Value у undefined

2019-02-17 09:05 UTC, Zwillinge commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
насколько вижу, там по-прежнему id

2019-02-17 09:08 UTC, Zwillinge commented on sources/views/detailes.js
> +			let id = this.getParam("id", true);
Посмотри внимательно на свой код: 
```
id = id || contacts.getFirstId(); //попытались получить 1 контакт 
if (!contacts.exists(id)) { //если него не нашли 
	id = contacts.getFirstId(); // то все равно выбираем первый контакт? 
}
```

И сеттить этот параметр здесь не надо - этим заниматься родительский модуль contacts, тебе здесь надо просто заполнить темплейт, если есть чем.

2019-02-17 09:22 UTC, Zwillinge commented
Осталось 3 открытых замечания + npm run lint, который сейчас не проходит

2019-02-17 12:41 UTC, VictorKholyavo commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
Если использовать:
`onAfterSelect: function(id) {
	const header =this.$scope("header");
	header.define({ template: this.getItem(id).value });
	header.refresh();
}`
то выдает ошибку TypeError: this.$scope is not a function.

2019-02-17 14:27 UTC, Zwillinge commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
не всё ж так буквально) 

если мы используем обычную функцию, но this укажет на компонент и у нас будет возможность получить объект айтема по id. а this.$scope - на JetView класс. так как из класса получить виджет по его id / localId?

2019-02-17 14:45 UTC, VictorKholyavo commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
Если использовать стрелочную функцию с событием onAfterSelect, то к header'у можно обратиться через `this.$$("header")`

2019-02-17 14:50 UTC, VictorKholyavo commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
При использовании обычной функции `function(id)` this будет относиться к menu, а this.$scope на Jetview класс

2019-02-17 16:31 UTC, VictorKholyavo commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
on: {
				onAfterSelect: (id) => {
					const header = this.$$("header");
					const menu = this.$$("menu")
					header.define({ template: menu.getItem(id).value });
					header.refresh();
				}
			}
Вот так работает

2019-02-17 20:59 UTC, Zwillinge commented on sources/views/top.js
> +					let name = id[0].toUpperCase() + id.slice(1);
Да, так тоже можно. В обычной ф-ции мы бы обращались к темплецту как `this.$scope.$$("header");`

2019-02-17 21:05 UTC, Zwillinge commented
теперь всё хорошо, убери только лишний файл start.js из views, пожалуйста

2019-02-18 08:37 UTC, HelgaListopad approved these changes

2019-02-18 08:48 UTC, merged