Stage 2
VictorKholyavo/basic-crm pull request #2
Opened 2019-02-19 16:06 UTC by VictorKholyavo

2019-02-20 16:10 UTC, HelgaListopad requested changes

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/contacts.js
> +										template: "<div class='list'><img src='#Photo#' class='photo_icon'></div><div class='overall list'><div class='title list'>#FirstName# #LastName#</div><div class='year'>#Company#</div> </di
Выглядит не очень хорошо, если фото нет.
Т.к. темплейт может быть задан функцией, этот вариант несложно отловить и выставить какую-нибудь картинку "по умолчанию", если obj.Photo == undefined

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/contacts.js
> +		this.on(this.app, "Close", () => {
Названия событий (особенно уровня app) долны быть более информативными

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/detailes.js
> +							template: "<div class='one'><span class='nameOfContact'>#FirstName# #LastName#<span><span><img  class='photo' src='#Photo#'></span><span>#status#</span></div><div class='one'><span></span><spa
Тоже не хватает обработки случая, когда в данных нет значения для Photo.
Поля `#template#` не должно быть - дату можно отформатировать прямо в темплейте.

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/formContact.js
> +		if(url[0].params.mode) {
Разбирать url - не очень хорошая идея. Используй `getParam`

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/formContact.js
> +			webix.promise.all ([
`contacts.getItem(id);` сейчас вне промиса, а это как раз то действие, ради которого промис и нужен.

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/formContact.js
> +		if(url[0].params.mode) {
Сейчас, если ты откроешь форму для edit, а потом нажмёшь на кнопку "Add contact"
- обе кнопки для сабмита (add/edit) будут спрятаны
- значения формы не очистятся, валидация не сбросится (в теории - валидации тоже не хватает, см. комментарии ниже)

Безопаснее всего было бы 
- прятать/показывать нужную кнопку в зависимости от mode (или его отстутствия)
- вызывать template.define в зависимости от mode (или его отстутствия)

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/formContact.js
> +		if (this.$$("formContact").validate()){
Не хватает правил валидации - всегда будет возвращаться true

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/formContact.js
> +	changePhoto (photo) {
Где вызывается эта функция? По идее, она и не нужна здесь

2019-02-20 16:10 UTC, HelgaListopad commented on sources/views/formContact.js
> +		this.app.callEvent("Close", []);
Раз это глобальное событие для app, назови его так, чтобы было понятно, что оно делает на уровне всего приложения.

2019-02-20 16:10 UTC, HelgaListopad commented on sources/models/contacts.js
> +			obj.template = templParser(webix.Date.copy(obj.Birthday));
Дату можно отформатировать прямо в темплейте, лучше не плодить лишние поля для этого.

2019-02-20 16:10 UTC, HelgaListopad commented on sources/models/contacts.js
> +const templParser = webix.Date.dateToStr("%Y %M %d");
Было бы здорово, если бы все даты в приложении имели один визуальный формат +/- время по необходимости. Пользователю сложно будет осознать, что день и месяц иногда меняются местами.
Плохой пример - таблица:
![image](https://user-images.githubusercontent.com/7587383/53105267-d4bfd980-3541-11e9-8b34-11a6a80633cc.png)


Пример форматирования для фильтров - https://snippet.webix.com/exbcjakm

2019-02-20 16:32 UTC, HelgaListopad commented
Сейчас не реализована часть сценария для [Add contact](https://hackmd.io/pedRvIz_QVK_PyyFscvGAA#Scenarios-general):

> the new contact will be added to the list and the form will be switched to a page with contact’s details.

После того, как контакт добавлен, он должен быть выбран в листе. 
Для этого нужно дождаться момента, когда при сохранении записи сервер вернёт для этой записи ID, а потом установить selection.

2019-02-21 11:39 UTC, VictorKholyavo commented on sources/views/contacts.js
> +		this.on(this.app, "Close", () => {
Исправил на CloseTheFormAndShowDetails

2019-02-21 11:43 UTC, VictorKholyavo commented on sources/views/formContact.js
> +		this.app.callEvent("Close", []);
Исправил на CloseTheFormAndShowDetails

2019-02-21 11:57 UTC, VictorKholyavo commented on sources/models/contacts.js
> +			obj.template = templParser(webix.Date.copy(obj.Birthday));
Исправил в функции в темплейте и удалил из коллекции

2019-02-21 12:08 UTC, VictorKholyavo commented on sources/models/contacts.js
> +const templParser = webix.Date.dateToStr("%Y %M %d");
Исправил на %d %M %Y

2019-02-21 12:09 UTC, VictorKholyavo commented on sources/views/formContact.js
> +	changePhoto (photo) {
Удалил

2019-02-21 13:25 UTC, VictorKholyavo commented on sources/views/formContact.js
> +		if(url[0].params.mode) {
Исправил на this.getParam("mode")

2019-02-21 14:28 UTC, VictorKholyavo commented on sources/views/contacts.js
> +										template: "<div class='list'><img src='#Photo#' class='photo_icon'></div><div class='overall list'><div class='title list'>#FirstName# #LastName#</div><div class='year'>#Company#</div> </di
Исправил на серый квадрат

2019-02-21 14:29 UTC, VictorKholyavo commented on sources/views/detailes.js
> +							template: "<div class='one'><span class='nameOfContact'>#FirstName# #LastName#<span><span><img  class='photo' src='#Photo#'></span><span>#status#</span></div><div class='one'><span></span><spa
Фото исправил на серый квадрат,
Поле template убрал

2019-02-21 14:29 UTC, VictorKholyavo commented on sources/views/formContact.js
> +		if(url[0].params.mode) {
Исправил на this.getParam("mode")

2019-02-21 14:33 UTC, VictorKholyavo commented on sources/views/formContact.js
> +		if (this.$$("formContact").validate()){
Добавил на все поля

2019-02-21 14:36 UTC, VictorKholyavo commented on sources/views/formContact.js
> +			webix.promise.all ([
Внес в промис

2019-02-22 09:26 UTC, HelgaListopad commented on sources/views/formContact.js
> +		if(url[0].params.mode) {
Минимум три действия (которые должны выполняться в любом случае) можно вынести за пределы блока if-else
```
form.clear();
form.clearValidation();
/**/
template.refresh();
```

2019-02-22 09:28 UTC, HelgaListopad commented on sources/views/formContact.js
> +		if (this.$$("formContact").validate()){
Если валидация не проходит, форма не должна закрываться - нужно дать пользователю исправить ошибки и сохранить данные.
А сейчас у тебя в любом случае вызывается `this.app.callEvent("CloseTheFormAndShowDetails", []);`, после чего форма закрывается.

2019-02-22 09:30 UTC, HelgaListopad commented on sources/models/contacts.js
> +const templParser = webix.Date.dateToStr("%Y %M %d");
Не везде - остаётся format для datepicker'ов и фильтра в таблице activities для contacts

2019-02-22 09:45 UTC, VictorKholyavo commented on sources/views/formContact.js
> +		if(url[0].params.mode) {
form.clear();
form.clearValidation(); вынес над if-else

template.refresh(); под ним

2019-02-22 09:53 UTC, VictorKholyavo commented on sources/views/formContact.js
> +		if (this.$$("formContact").validate()){
Внес this.app.callEvent("CloseTheFormAndShowDetails", []); в if (this.$$("formContact").validate()) и форма не закрывается если не пройдена проверка

2019-02-22 09:55 UTC, VictorKholyavo commented on sources/models/contacts.js
> +const templParser = webix.Date.dateToStr("%Y %M %d");
Исправил

2019-02-22 11:59 UTC, HelgaListopad approved these changes

2019-02-22 11:59 UTC, merged